
apiVersion: v1
kind: Service
metadata:
  name: jpetstorewar
  labels:
    app: jpetstorewar
spec:
  ports:
    - port: 9080
  selector:
    app: jpetstorewar
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jpetstorewar
  name: jpetstorewar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jpetstorewar
    spec:
      containers:
      - image: mycluster.icp:8500/default/jpetstorewar:latest
        name: jpetstorewar
        ports:
        - containerPort: 9080
          protocol: TCP
